# Site settings
title: ahels blog
# email: your-email@domain.com
description: "This blog is about books I have read and useful thing I have found out just for myself to remember stuff."
# baseurl: ""
# url: "http://yourdomain.com"
# twitter_username: jekyllrb
github_username:  4hel

# Build settings
markdown: kramdown
permalink: /:categories/:title.html
